---
title: "Time series analysis, 7.5 hp "
subtitle: "Inlämningsuppgift 2, 2.5 hp"
author: 
- Sverker Berggren
- Love Alfredsson
- Emil Möller
date: last-modified
format: 
  html:
    self-contained: true
  #pdf: default
language: 
  title-block-author-single: " "
crossref-fig-title: "Figur"
title-block-banner-color: Primary
title-block-published: "Publicerad"
author-title: "Gruppmedlemmar"
title-block-banner: true
editor: source
---

```{r}
#| output: false
#| echo: false
library(dplyr)
library(ggplot2)
library(tidyverse)
library(jsonlite)
library(lubridate)

```

# Uppgift 1

```{r}
json <- fromJSON("data/dow_stock_price.json")

dow_tibble <- json$DOW  %>%   as_tibble()

dow_tibble = dow_tibble %>% rename(high = h, open = o, close = c,low = l,date = t,volume = v, number_of_trades = n,volume_weighted_average_price = vw)
dow_tibble = dow_tibble %>% mutate(date = as.Date(date))
futures_tibble <- stream_in(file("data/glbx-mdp3-20190402-20260103.ohlcv-1d.json"),verbose = FALSE)%>% unnest_wider(hd) %>% as_tibble()

```

```{r}
futures_tibble = futures_tibble %>%
  mutate(
    ts_event = as.Date(ts_event),
    open   = as.numeric(open),
    high   = as.numeric(high),
    low    = as.numeric(low),
    close  = as.numeric(close),
    volume = as.numeric(volume)
  )
```

```{r}
oil_tibble = futures_tibble %>%  filter(grepl("^CL[A-Z][0-9]$", symbol))
oil_daily = oil_tibble %>%  group_by(ts_event) %>% slice_max(volume,n=1,with_ties = FALSE) %>% ungroup() 
oil_daily = oil_daily %>% rename(date = ts_event,close_oil = close)

natural_gas_tibble = futures_tibble %>%  filter(grepl("^NG[A-Z][0-9]$", symbol))
natural_gas_tibble = natural_gas_tibble %>%  group_by(ts_event) %>% slice_max(volume,n=1,with_ties = FALSE) %>% ungroup() 
natural_gas_tibble = natural_gas_tibble %>% rename(date = ts_event,close_gas = close)


dow_tibble = dow_tibble %>% left_join(select(oil_daily,date,close_oil),by = "date",)
dow_tibble = dow_tibble %>% left_join(select(natural_gas_tibble,date,close_gas),by = "date",)

ggplot(dow_tibble, aes(date)) +
   geom_line(aes(y = close, colour = "stock close")) + geom_line(aes(y = close_oil, colour = "oil close")) + geom_line(aes(y = close_gas, colour = "gas close")) +
   labs(title = "Daily Front-Month Crude Oil Price")


```


https://blog.bizvibe.com/blog/plastic-manufacturing-companies
https://investors.dow.com/en/news/news-details/2025/Dow-reports-third-quarter-2025-results/default.aspx
https://www.eia.gov/tools/faqs/faq.php?id=34&t=6

https://databento.com/portal/browse
https://docs.alpaca.markets/reference/stockbars